spring:
  application:
    name: "API Service"
  # RabbitMQ properties
  rabbitmq:
    host: localhost
    listener:
        default-requeue-rejected: false

endpoints:
  enabled: true
  sensitive: false

info:
  java:
    source: "${java.version}"

logging:
  level:
    root: INFO

management:
  info:
    build:
      enabled: true
    git:
      mode: full

server:
  context-path: /FastDeliveryPizza
  port: 8089
  address: localhost

